const SET_FORM_DATA = 'SET_FORM_DATA';
const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
const SET_FORM_EXTRA_PROPS = 'SET_FORM_EXTRA_PROPS';

export { SET_FORM_DATA, SET_FORM_ERRORS, SET_FORM_EXTRA_PROPS };
